/*
 * KMapSym
 *
 * Copyright (C) 2026 KO Myung-Hun <komh78@gmail.com>
 *
 * This file is a part of K MapSym
 *
 * This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://www.wtfpl.net/ for more details.
 */

/** @file */

#include "kmapparser.h"
#include "kibmmapparser.h"
#include "kwatcommapparser.h"
#include "ksymwriter.h"
#include "kverbose.h"

#include <iostream>
#include <filesystem>

#include <string_view>

/**
 * .MAP file parser type
 */
enum class KMapParserType {
    None,   ///< Unknown
    Ibm,    ///< IBM map file genereated by link386 and ilink
    Watcom  ///< Watcom map file generated by wlink
};

#define verb KVerbose::instance()

/**
 * Show usage
 *
 * @param[in] me Program name
 */
static void showUsage()
{
    verb.out() << "\
Usage: kmapsym map_type [options] filename[.map]\n\
map_type:\n\
    -i: IBM map file (default)\n\
    -w: Watcom map file\n\
options:\n\
    -a: Omit alphabetical sorting of symbols\n\
    -l: Produce verbose listing\n\
    -ll: Produce more verbose listing\n\
    -n: Include source code line numbers in .SYM file (ignored)\n\
";
}

int main( int argc, char *argv[])
{
    std::string arg;
    std::filesystem::path mapPath;

    KMapParserType parserType = KMapParserType::Ibm;
    std::unique_ptr< KMapParser > parser;

    bool omitAlphaSort = false;

    if( argc < 2 )
    {
        showUsage();

        return 1;
    }

    for( int i = 1; i < argc; i++ )
    {
        arg = argv[ i ];
        if( arg.compare("-i") == 0 )
            parserType = KMapParserType::Ibm;
        else if( arg.compare("-w") == 0 )
            parserType = KMapParserType::Watcom;
        else if( arg.compare("-a") == 0 )
            omitAlphaSort = true;
        else if( arg.compare("-l") == 0 )
             verb.level( KVerbose::Level::Info );
        else if( arg.compare("-ll") == 0 )
            verb.level( KVerbose::Level::Debug );
        else if( arg.compare("-n") == 0 )
            /* ignore */;
        else
        {
            if( !mapPath.empty())
            {
                verb.err() << "Multiple file names specified!!!\n";
                showUsage();

                return 1;
            }

            mapPath = arg;
        }
    }

    if( mapPath.empty())
    {
        verb.err() << "Missing .MAP file name!!!\n";
        showUsage();

        return 1;
    }

    if( mapPath.extension().empty())
        mapPath += ".map";

    if( parserType == KMapParserType::Ibm )
        parser = std::make_unique< KIbmMapParser >( mapPath.string());
    else
        parser = std::make_unique< KWatcomMapParser >( mapPath.string());

    if( !parser )
    {
        verb.err() << "Out of memory!!!\n";

        return 1;
    }

    if( parser->open() && parser->parse())
    {
        auto symPath = mapPath;
        symPath.replace_extension(".sym");

        KSymWriter writer( symPath.string());

        if( !writer.open())
            return 1;

        writer.setOmitAlphaSort( omitAlphaSort );

        verb.info() << "Building " << symPath.string() << "\n"
                    << mapPath.string() << "\n";

        int bits = 16;
        for( const auto& seg: parser->segments())
        {
            if( seg.nBits == 32 )
                bits = 32;

        }
        verb.info() << bits << "-bit LE map\n";

        verb.debug() << "MODULE: " << parser->moduleName() << "\n"
                     << "\n";

        writer.setModuleName( parser->moduleName());

        for( const auto& seg: parser->segments())
        {
            verb.debug() << "SEGMENT: "
                         << seg.addr << "\t"
                         << seg.length << "\t"
                         << seg.name << "\t"
                         << seg.className << "\t"
                         << seg.nBits << "-Bit" << "\n";

            writer.addSegment( seg );
        }

        verb.debug() << "\n";

        for( const auto& group: parser->groups())
        {
            verb.debug() << "GROUP: "
                         << group.addr << "\t"
                         << group.length << "\t"
                         << group.name << "\n";

            writer.addGroup( group );
        }

        verb.debug() << "\n";

        for( const auto& pub: parser->publicsByName())
        {
            verb.debug() << "PUBLIC BY NAME: "
                         << pub.addr << "\t"
                         << pub.name << "\n";
        }

        verb.debug() << "\n";

        for( const auto& pub: parser->publicsByValue())
        {
            verb.debug() << "PUBLIC BY VALUE: "
                         << pub.addr << "\t"
                         << pub.name << "\n";

            writer.addSymbol( pub );
        }

        verb.debug() << "\n";

        for( const auto& imp: parser->imports())
        {
            verb.debug() << "IMPORT: "
                         << imp.addr << "\t"
                         << imp.name << "\t"
                         << imp.dllName << "\t"
                         << imp.dllOrdOrExp << "\n";
        }

        verb.out() << "\n";

        verb.out() << "Program entry point at " << parser->entryPoint() << "\n";

        writer.setEntryPoint( parser->entryPoint());

        writer.write();
    }

    return 0;
}
