/*
 * KMapSym
 *
 * Copyright (C) 2026 KO Myung-Hun <komh78@gmail.com>
 *
 * This file is a part of K MapSym
 *
 * This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://www.wtfpl.net/ for more details.
 */

/** @file */

#include "kmapparser.h"
#include "kibmmapparser.h"
#include "kwatcommapparser.h"
#include "ksymwriter.h"

#include <iostream>
#include <filesystem>

#include <string_view>

/**
 * .MAP file parser type
 */
enum class KMapParserType {
    None,   ///< Unknown
    Ibm,    ///< IBM map file genereated by link386 and ilink
    Watcom  ///< Watcom map file generated by wlink
};

/**
 * Show usage
 *
 * @param[in] me Program name
 */
static void showUsage()
{
    std::cout << "\
Usage: kmapsym map_type filename[.map]\n\
map_type:\n\
    -i: IBM map file (default)\n\
    -w: Watcom map file\n\
";
}

int main( int argc, char *argv[])
{
    std::string arg;
    std::filesystem::path mapPath;

    KMapParserType parserType = KMapParserType::Ibm;
    std::unique_ptr< KMapParser > parser;

    if( argc < 2 )
    {
        showUsage();

        return 1;
    }

    for( int i = 1; i < argc; i++ )
    {
        arg = argv[ i ];
        if( arg.compare("-i") == 0 )
            parserType = KMapParserType::Ibm;
        else if( arg.compare("-w") == 0 )
            parserType = KMapParserType::Watcom;
        else
        {
            if( !mapPath.empty())
            {
                std::cerr << "Multiple file names specified!!!\n";
                showUsage();

                return 1;
            }

            mapPath = arg;
        }
    }

    if( mapPath.empty())
    {
        std::cerr << "Missing .MAP file name!!!\n";
        showUsage();

        return 1;
    }

    if( mapPath.extension().empty())
        mapPath += ".map";

    if( parserType == KMapParserType::Ibm )
        parser = std::make_unique< KIbmMapParser >( mapPath.string());
    else
        parser = std::make_unique< KWatcomMapParser >( mapPath.string());

    if( !parser )
    {
        std::cerr << "Out of memory!!!\n";

        return 1;
    }

    if( parser->open() && parser->parse())
    {
        auto symPath = mapPath;
        symPath.replace_extension(".sym");

        KSymWriter writer( symPath.string());

        if( !writer.open())
            return 1;

#ifdef DEBUG
        std::cout << "MODULE: " << parser->moduleName() << "\n";
        std::cout << "\n";
#endif

        writer.setModuleName( parser->moduleName());

        for( auto group: parser->groups())
        {
#ifdef DEBUG
            std::cout << "GROUP: "
                      << group.addr << "\t"
                      << group.length << "\t"
                      << group.name << "\n";
#endif

            writer.addGroup( group );
        }
#ifdef DEBUG
        std::cout << "\n";
#endif

        for( auto seg: parser->segments())
        {
#ifdef DEBUG
            std::cout << "SEGMENT: "
                      << seg.addr << "\t"
                      << seg.length << "\t"
                      << seg.name << "\t"
                      << seg.className << "\t"
                      << seg.nBits << "-Bit" << "\n";
#endif

            writer.addSegment( seg );
        }
#ifdef DEBUG
        std::cout << "\n";
#endif

#ifdef DEBUG
        for( auto pub: parser->publicsByName())
        {
            std::cout << "PUBLIC BY NAME: "
                      << pub.addr << "\t"
                      << pub.name << "\n";
        }
        std::cout << "\n";
#endif

        for( auto pub: parser->publicsByValue())
        {
#ifdef DEBUG
            std::cout << "PUBLIC BY VALUE: "
                      << pub.addr << "\t"
                      << pub.name << "\n";
#endif

            writer.addSymbol( pub );
        }
#ifdef DEBUG
        std::cout << "\n";
#endif

#ifdef DEBUG
        for( auto imp: parser->imports())
        {
            std::cout << "IMPORT: "
                      << imp.addr << "\t"
                      << imp.name << "\t"
                      << imp.dllName << "\t"
                      << imp.dllOrdOrExp << "\n";
        }
        std::cout << "\n";

        std::cout << "ENTRY POINT: " << parser->entryPoint() << "\n";
        std::cout << "\n";
#endif

        writer.setEntryPoint( parser->entryPoint());

        writer.write();
    }

    return 0;
}
